# Testes para verificar o entendimento da função order points

In [8]:
import numpy as np

In [9]:
def order_points(pts):
   # initializing the list of coordinates to be ordered
   rect = np.zeros((4, 2), dtype = "float32")

   s = pts.sum(axis = 1)

   # top-left point will have the smallest sum
   rect[0] = pts[np.argmin(s)]

   # bottom-right point will have the largest sum
   rect[2] = pts[np.argmax(s)]

   '''computing the difference between the points, the
   top-right point will have the smallest difference,
   whereas the bottom-left will have the largest difference'''
   diff = np.diff(pts, axis = 1)
   print(diff)
   rect[1] = pts[np.argmin(diff)]
   rect[3] = pts[np.argmax(diff)]

   # returns ordered coordinates
   return rect

In [10]:
rect_vertical = np.array([
    [0, 0],
    [0, 150],
    [100, 150],
    [100, 0]
])
print(order_points(rect_vertical))

[[   0]
 [ 150]
 [  50]
 [-100]]
[[  0.   0.]
 [100.   0.]
 [100. 150.]
 [  0. 150.]]


In [12]:
rect_horizontal = np.array([
    [0, 0],
    [150, 0],
    [150, 100],
    [0, 100]
])
print(order_points(rect_horizontal))

[[   0]
 [-150]
 [ -50]
 [ 100]]
[[  0.   0.]
 [150.   0.]
 [150. 100.]
 [  0. 100.]]
